image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
  - build
  - test
  - deploy
build:
  stage: build
  variables:
    build_path: "$project/src/$project"
  script:
    - "cd $build_path"
    - "dotnet build"

test:
  stage: test
  variables:
    test_path: "$project/test/$project.Tests"
  script:
    - "cd $test_path"
    - "dotnet test"
    
deploy:
  stage: deploy
  script:
    - dotnet pack -c Release
    - dotnet nuget add source "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/nuget/index.json" --name gitlab --username gitlab-ci-token --password $CI_JOB_TOKEN --store-password-in-clear-text
    - dotnet nuget push "bin/Release/*.nupkg" --source gitlab
  only:
    - master
    - development
    - tags
